### ISSUE TITLE
AxiosError

### ISSUE THREAD

**Issue by segunh** [shahriarsajeeb/Eshop-tutorial#2]
![Screenshot (4)](https://github.com/shahriarsajeeb/Eshop-tutorial/assets/76851676/315a47f3-67dc-4bc3-ab32-00c4ecede346)

Please i keep having the attached error, i need elp.

**Comment by KoushikDuttaHih7** [comment]
@segunh Found any solution???

**Comment by segunh** [comment]
I haven't, everything worked to the point of signup when it upload picture to the upload folder. My problem started from sending email notifications after sign up.

**Comment by KoushikDuttaHih7** [comment]
I guess, I found the solution... Just put accept="*" in Frontend form ... upload a photo

**Comment by shahriarsajeeb** [comment]
The missing part: https://www.youtube.com/watch?v=nQnneTf_tYU

**Comment by segunh** [comment]
Thank you
