### ISSUE TITLE
Email verification not working

### ISSUE THREAD

**Issue by mathiasabdissa** [shahriarsajeeb/Eshop-tutorial#22]
Both the frontend and the backend worked smoothly but facing an issue with login and sign up.

**Comment by mathiasabdissa** [comment]
![Screenshot from 2023-10-31 09-36-03](https://github.com/shahriarsajeeb/Eshop-tutorial/assets/43569821/aee14d9e-382f-4a5e-90fe-8ad3abb1e7a8)

**Comment by shahriarsajeeb** [comment]
Don't use vite. Use Pure React js it will fix it.

**Comment by kyuna0312** [comment]
i am using pure react but it's getting error on email verification it's getting Missing credentials for "PLAIN"  500 error what should i do ???

**Comment by kyuna0312** [comment]
SMPT_SERVICE = gmail
SMPT_HOST = smtp.gmail.com
SMPT_PORT = 465
SMTP_PASSWORD = 'sgupdcejrkybzphw'
SMTP_MAIL = "tiahalibel6@gmail.com" this is my verification config same like your code ?

**Comment by kyuna0312** [comment]
avatar	"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAVEAAADnCAYAAACnkmWeAAABWmlDQ1BJQ0MgUHJvZmlsZQAAKJF1kMErg3EYxz+brRVrUUhy2MFFjda2knKZtVBobcY4efduRrb59W6Sm5STi4P8B8RJSSk5+BOUopzc/AFqF9breTdsI099+3769jxPTw/Y3ZpSeQdQKJaN+OSEN7W07HW94qafHoKg6SUVjsVmpIVvb63KIzbLH4atXecr+3N66nJsJHTlNHfGl/72t1R7JlvSxT9EIV0ZZbD5hWPbZWXxrnC3IUcJH1mcq/OZxek639Z65uMR4XvhTn1Nywi/CPvSTXmuiQv5Lf3rBut6d7aYTIj3iQYIkyAp8rIgHGCUKFNE/5kJ1WYibKLYwWCdHGuUZTosiSJPVniaIjoj+IQD+EVB69e/f9jINi5gdBbsB41s9QRuPNDb1cgG98Bj5YdKM7Sfz9oqjtJqMFDnjmtwHpvm2yK4h…sq9nGOqSHlcaqDFNSBBtMVV3MQKmAUT4U8WB9vzfRj00RWle411YwfMapmieHfSdh5Zn0ejR4+lDevX0tEfDosA+XsGDxGj7hh0wij6/r27dasTluL9PKquZr54gPqX69ayBVzfxde7WGcHsaifr/mUJkxM4FH/JeIMQqQ2fLlWbCft3EFeXp0IEwjgi4XPduu3W9g3mq5TityUGmhdDdglZXLrqrhj1ubh6cUgVqIHyvMWLKbY2Dh68YX/4t5+rfAvw0XSFHFjtwSAt8rgHwLKgn9UrXbnuNqiphQt75EasKoGpCVqVXXaT2ENAhiDaFMBFFpUYlONaRTWdIP1G7tRHpMaaAENSBBtAaXassjlb/zNJtX/9/PPirjRC+czhRXa2u1A/VKkBmyhAdmdt4XWZZ1SA1IDHUYD9cF/HeaR5INIDUgNSA20ngYkiLaermVNUgNSAx1QAxJEO+BLlY8kNSA10Hoa+H+s1xBCclOm0gAAAABJRU5ErkJggg=="
email	"khatanzorigb@gmail.com"
name	"marin"
password	"1234". this is my request sending request it's getting 500 in send smtp

**Comment by mathiasabdissa** [comment]
> Don't use vite. Use Pure React js it will fix it.

Thank you @shahriarsajeeb has worked for me fine now.
